# Generated by Django 3.1.7 on 2021-04-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('major', models.CharField(max_length=100, null=True)),
                ('housing', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selldonate', models.CharField(choices=[('SO', 'Select One'), ('SE', 'Selling'), ('DO', 'Donating')], default='Select One', max_length=2, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('edition', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(choices=[('SO', 'Select One'), ('NE', 'New'), ('GR', 'Great'), ('GO', 'Good'), ('AV', 'Average'), ('PO', 'Poor')], default='Select One', max_length=2, null=True)),
                ('field', models.CharField(choices=[('SO', 'Select One'), ('ART', 'Arts'), ('MSC', 'Music'), ('HST', 'History'), ('LNG', 'Languages'), ('LAW', 'Law'), ('PHL', 'Philosophy'), ('THE', 'Theology'), ('ECN', 'Economics'), ('PLS', 'Political Science'), ('PSY', 'Psychology'), ('SOC', 'Sociology'), ('NUR', 'Nursing'), ('BIO', 'Biology'), ('CHM', 'Chemistry'), ('PHY', 'Physics'), ('ENG', 'Engineering'), ('CSC', 'Computer Science'), ('MTH', 'Mathematics'), ('BUS', 'Business'), ('FIN', 'Finance'), ('ACT', 'Accounting')], default='Select One', max_length=4, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
