# Generated by Django 3.1.7 on 2021-04-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN13',
        ),
    ]
