# Generated by Django 3.1.7 on 2021-04-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0002_auto_20210414_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
