# Generated by Django 3.1.7 on 2021-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0014_remove_book_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
