# Generated by Django 3.1.7 on 2021-05-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0018_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed (pending)', 'Completed (pending)'), ('Completed', 'Completed')], default='In progress', max_length=40, null=True),
        ),
    ]
