# Generated by Django 3.1.7 on 2021-05-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0021_auto_20210509_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='owner',
            new_name='user',
        ),
    ]
