# Generated by Django 3.1.7 on 2021-05-09 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbapp', '0022_auto_20210509_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='numberofratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
