# Generated by Django 3.1.7 on 2021-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0030_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyerhasrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerhasrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Created', max_length=40, null=True),
        ),
    ]
