# Generated by Django 3.1.7 on 2021-05-12 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0031_auto_20210512_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
