# Generated by Django 3.1.7 on 2021-05-12 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0032_transaction_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
