# Generated by Django 3.1.7 on 2021-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0034_merge_20210512_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
