# Generated by Django 3.1.7 on 2021-05-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0024_auto_20210510_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='buyerrating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='numberofratings',
            new_name='numberofbuyerratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='numberofsellerratings',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='sellerrating',
            field=models.FloatField(default=5.0),
        ),
    ]
