# Generated by Django 3.1.7 on 2021-05-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0027_reported'),
        ('bbapp', '0030_message_recipient'),
    ]

    operations = [
    ]
