# Generated by Django 3.1.7 on 2021-05-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0031_merge_20210512_1412'),
        ('bbapp', '0033_auto_20210512_1657'),
    ]

    operations = [
    ]
