# Generated by Django 3.1.7 on 2021-05-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0035_book_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported',
            name='reportedbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportedbook', to='bbapp.book'),
        ),
        migrations.AddField(
            model_name='reported',
            name='reportedtransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbapp.transaction'),
        ),
    ]
